apiVersion: v1
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type application/json;

        location / {
            return 200 '{"node":"minikube","namespace":"default","deployment":"canary Ver2.0","pod": "$hostname"}\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap-canary
