apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: deploy_edit_user
subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: User
   name: deploy_edit
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: edit-role
