apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: prod_admin_user
 namespace: prod
subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: User
   name: prod_admin
   namespace: prod
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
