apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: deploy_view_user
subjects:
 - apiGroup: rbac.authorization.k8s.io
   kind: User
   name: deploy_view
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: view-role
